// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHibpqjif1bqxDVFdeZvELoao1H5XP4wI',
    appId: '1:842326537974:web:b63f5240bd33e09e25ded7',
    messagingSenderId: '842326537974',
    projectId: 'night-club-bbc5e',
    authDomain: 'night-club-bbc5e.firebaseapp.com',
    storageBucket: 'night-club-bbc5e.appspot.com',
    measurementId: 'G-GGJMZZLT6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfB0uVpUuyuGRIqrdJdoul7Y0zdA5UyGw',
    appId: '1:842326537974:android:26f0412e080a6b1625ded7',
    messagingSenderId: '842326537974',
    projectId: 'night-club-bbc5e',
    storageBucket: 'night-club-bbc5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuH3yTN5yx_v25gcJD1-yVlL7b-1JXgyo',
    appId: '1:842326537974:ios:62922860fa32d6fb25ded7',
    messagingSenderId: '842326537974',
    projectId: 'night-club-bbc5e',
    storageBucket: 'night-club-bbc5e.appspot.com',
    iosBundleId: 'com.example.instagramRiverpodClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuH3yTN5yx_v25gcJD1-yVlL7b-1JXgyo',
    appId: '1:842326537974:ios:62922860fa32d6fb25ded7',
    messagingSenderId: '842326537974',
    projectId: 'night-club-bbc5e',
    storageBucket: 'night-club-bbc5e.appspot.com',
    iosBundleId: 'com.example.instagramRiverpodClone',
  );
}
